---
title: "U.S. Tweet data"
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "Project Website", href: "https://github.com/k-maciejewski/p8105_final_website", align: left }
    source_code: "https://github.com/k-maciejewski/p8105_final_shinyUS"
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(haven)
library(dplyr)
library(knitr)
library(ggthemes)
library(plotly)
library(tidytext)
library(shiny)
library(maptools)
library(gpclib)
library(sp)
library(stringi)
library(choroplethr)
library(choroplethrMaps)
library(syuzhet)
library(dplyr)
library(scales)
library(tidyverse)
library(tidytext)
library(RColorBrewer)
library(plotly)
library(lubridate)
```

```{r load tweet data, cache = TRUE}
# The sentiment function takes a really long time so I created a new data file so you don't have to run it
us_tweets <- read_csv("us_tweets.csv") 

#gets rid of non alphabetic characters  
us_tweets$tweet_content_stripped <- gsub("[^[:alpha:] ]", "",
                                         us_tweets$tweet_content) 


#removes all words that are 1-2 letters long
us_tweets$tweet_content_stripped <- gsub(" *\\b[[:alpha:]]{1,2}\\b *", " ",
                                         us_tweets$tweet_content_stripped) 
```

```{r create sentiment totals}
sentimentTotals <- data.frame(colSums(us_tweets[,c(20:27)]))

names(sentimentTotals) <- "count"

sentimentTotals <- cbind("sentiment" = rownames(sentimentTotals),
                         sentimentTotals)
```


```{r Converts to long format}
us_tweets_long <- gather(us_tweets, sentiment, count, anger:trust, 
                         factor_key = TRUE)
```

```{r number of tweets per hour}
us_tweets$hour <- hour(as.POSIXct(us_tweets$hour, format = " %H:%M"))

```

Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made for the final project of [Jeff Goldsmith's Data Science I class](http://jeffgoldsmith.com/DSI/final_project.html) in the Department of Biostatistics at Columbia University. 

This page investigates tweet sentiments over the enire U.S. during April 14-15, 2016. The data analyzed is from [here]( http://followthehashtag.com/datasets/free-twitter-dataset-usa-200000-free-usa-tweets/).

It was created by [Kaitlin Maciejewski](https://github.com/k-maciejewski) and ...


```{r, eval = F}
sentiments = us_tweets_long %>% distinct(sentiment) %>% pull()

checkboxGroupInput("sentiment_choice", label = h3("Select Sentiment"),
            choices = sentiments, selected = "anger")

hr()

us_tweets_neg_pos <- gather(us_tweets, neg_pos, count, negative:positive, 
                         factor_key = TRUE)

pos_neg = us_tweets_neg_pos %>% distinct(neg_pos) %>% pull()

radioButtons("pos_neg", label= h3("Select Positive or Negative Tweets"), choices = pos_neg, selected = NULL,
  inline = FALSE, width = NULL, choiceNames = NULL, choiceValues = NULL)

hr()

# set hour of the day
# min_hour = us_tweets_long %>% filter(sentiment == input$sentiment_choice) %>% select(hour) %>%  as.POSIXct(min())
# 
# max_hour = us_tweets_long %>% filter(sentiment == input$sentiment_choice) %>% select(hour) %>%  as.POSIXct(max())

hours = us_tweets %>% distinct(hour) %>% pull()

# sliderInput widget
sliderInput("hour_choice", label = h3("Choose hour"), min=min(hours),
            max= max(hours),
            value=c("1","2"))

hr()

```

Row {.tabset .tabset-fade } 
-----------------------------------------------------------------------

### Tweet Positivity or Negitivity

```{r np_widgets}
us_tweets_neg_pos <- gather(us_tweets, neg_pos, count, negative:positive, 
                         factor_key = TRUE)

pos_neg = us_tweets_neg_pos %>% distinct(neg_pos) %>% pull()

radioButtons("pos_neg", label= h3("Select Positive or Negative Tweets"), choices = pos_neg, selected = NULL,
  inline = FALSE, width = NULL, choiceNames = NULL, choiceValues = NULL)

hr()
```

```{r, eval = T}
renderPlotly({
#positive score
us_tweets_neg_pos %>% filter(neg_pos == input$pos_neg) %>%
  filter(country == "US") %>% 
  mutate(text_label = str_c("sentiment: ", neg_pos, '\nlocation: ', place_as_appears_on_bio)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~neg_pos, colors = "Set2", text = ~text_label)
})
```


### Tweet Sentiments
```{r sent_widget}
sentiments = us_tweets_long %>% distinct(sentiment) %>% pull()

checkboxGroupInput("sentiment_choice", label = h3("Select Sentiment"),
            choices = sentiments, selected = "anger")

hr()
```

```{r, eval = T}
#name of sentiment
renderPlotly({
#name of sentiment, ggplot
us_tweets_long %>%  filter(sentiment == input$sentiment_choice) %>% 
  filter(country == "US") %>% 
  filter(count > 0) %>% 
  mutate(text_label = str_c("sentiment: ", sentiment, '\nlocation: ', place_as_appears_on_bio)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~sentiment, text = ~text_label)
})
```


### Tweets per hour

```{r hr_widget}
hours = us_tweets %>% distinct(hour) %>% pull()

# sliderInput widget
sliderInput("hour_choice", label = h3("Choose hour"), min=min(hours),
            max= max(hours),
            value=c("1","5"))

hr()
```


```{r map tweets per hour, eval = T}
renderPlotly({
#map interactive tweets per hour in dashboard

us_tweets_long %>%
  filter(country == "US") %>%  filter(sentiment == input$sentiment_choice) %>% filter(hour == input$hour_choice)%>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~sentiment, text = ~hours)
})
```

### State Heat Maps

```{r heat map, eval = FALSE}
state_tweets = us_tweets %>%
  select("longitude", "latitude")

latlong2state <- function(state_tweets) {
    states <- map('state', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    states_tweets_SP <- SpatialPoints(state_tweets, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))
    
    indices <- over(states_tweets_SP, states_sp)

    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stateNames[indices]
}

state_name = latlong2state(state_tweets)

us_tweets = cbind(state_name, us_tweets)
```

```{r, eval= FALSE}
us_sentiments = us_tweets %>%
  filter(country == "US") %>%
  select(c(1, 21:30)) %>%
  na.omit(state_name) %>%
  group_by(state_name) %>%
  summarise_all(funs(sum)) %>%
  mutate(positive = as.numeric(positive),
         negative = as.numeric(negative))

```


```{r, eval = FALSE}
us_sentiments %>%
  select("state_name", "negative") %>%
  rename(region = state_name, value = negative) %>%
  state_choropleth(title = "Negative Sentiment across the U.S.",
                   legend = "Sentiment Score")  

us_sentiments %>%
  select("state_name", "positive") %>%
  rename(region = state_name, value = positive) %>%
  state_choropleth(title = "Positive Sentiment Across the U.S.",
                   legend = "Sentiment Score")
```

